Repository CMU-313/fall22-hw3-team-sweg, pull requests merged in 2022-10, with the labels that each got.

#16 Add pull request template
  .github/pull_request_template.md
Labels: chore

#17 Add tests on PR
  .github/workflows/build-deploy.yml
Labels: build

#20 Add API to get the number of unread messages
  docs-core/pom.xml
  docs-core/src/main/java/com/sismics/docs/core/event/DocumentAssignedAsyncEvent.java
  docs-core/src/main/java/com/sismics/docs/core/event/DocumentCommentedAsyncEvent.java
  docs-core/src/main/java/com/sismics/docs/core/event/DocumentReviewedAsyncEvent.java
  docs-core/src/main/java/com/sismics/docs/core/listener/async/MessageAsyncListener.java
  docs-core/src/main/java/com/sismics/docs/core/model/context/AppContext.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/CommentResource.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestMessageResource.java
  pom.xml
Labels: enhancement

#21 Create `messages` table
  .github/workflows/build-deploy.yml
  .github/workflows/build-test.yml
  docs-core/src/main/java/com/sismics/docs/core/constant/MessageType.java
  docs-core/src/main/java/com/sismics/docs/core/dao/MessageDao.java
  docs-core/src/main/java/com/sismics/docs/core/model/jpa/Message.java
  docs-core/src/main/resources/config.properties
  docs-core/src/main/resources/db/update/dbupdate-028-0.sql
  docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestMessage.java
  docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestUser.java
  docs-web/src/dev/resources/config.properties
  docs-web/src/prod/resources/config.properties
Labels: enhancement

#23 Fix CI push badge commit
  .github/workflows/build-deploy.yml
Labels: bug, build

#25 Create message entity on events
  docs-core/src/main/java/com/sismics/docs/core/listener/async/MessageAsyncListener.java
Labels: enhancement

#26 Unread message extractor
  docs-core/src/main/java/com/sismics/docs/core/dao/MessageDao.java
  docs-core/src/main/java/com/sismics/docs/core/listener/async/MessageAsyncListener.java
  docs-core/src/test/java/com/sismics/docs/core/dao/jpa/TestMessage.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestMessageResource.java
Labels: enhancement

#27 Add inbox page and inbox tab to teedy navbar
  docs-web/src/main/webapp/src/app/docs/app.js
  docs-web/src/main/webapp/src/app/docs/controller/inbox/Inbox.js
  docs-web/src/main/webapp/src/index.html
  docs-web/src/main/webapp/src/partial/docs/inbox.default.html
  docs-web/src/main/webapp/src/partial/docs/inbox.html
Labels: enhancement

#28 Add messages api
  docs-core/src/main/java/com/sismics/docs/core/dao/MessageDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/criteria/MessageCriteria.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/MessageDto.java
  docs-core/src/main/java/com/sismics/docs/core/listener/async/MessageAsyncListener.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/test/java/com/sismics/docs/rest/TestMessageResource.java
Labels: enhancement

#30 Connect unread message count to show on the navbar
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/main/webapp/src/app/docs/controller/Navigation.js
  docs-web/src/main/webapp/src/index.html
Labels: enhancement

#34 Add document assigned message
  docs-web/src/main/java/com/sismics/docs/rest/resource/AclResource.java
  docs-web/src/main/webapp/package-lock.json
  docs-web/src/test/java/com/sismics/docs/rest/TestAclResource.java
Labels: enhancement

#36 Fix multiple long polling from the same client
  docs-core/src/main/java/com/sismics/docs/core/listener/async/MessageAsyncListener.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
Labels: bug

#37 Create inbox messages
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/main/webapp/package-lock.json
  docs-web/src/main/webapp/src/app/docs/controller/inbox/Inbox.js
  docs-web/src/main/webapp/src/app/docs/controller/inbox/InboxDefault.js
  docs-web/src/main/webapp/src/index.html
  docs-web/src/main/webapp/src/partial/docs/inbox.html
  docs-web/src/main/webapp/src/style/bootstrap.css
Labels: enhancement

#39 Add reading message
  docs-core/src/main/java/com/sismics/docs/core/dao/MessageDao.java
  docs-core/src/main/java/com/sismics/docs/core/dao/dto/MessageDto.java
  docs-web/src/main/java/com/sismics/docs/rest/resource/MessageResource.java
  docs-web/src/main/webapp/package-lock.json
  docs-web/src/main/webapp/src/app/docs/controller/Navigation.js
  docs-web/src/main/webapp/src/app/docs/controller/inbox/Inbox.js
  docs-web/src/main/webapp/src/partial/docs/inbox.html
Labels: enhancement
